# -*- coding: utf-8 -*-
"""main_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aElOofc8y2ap3nmKcWpCrqYtjzjKhJEa
"""

import yfinance as yf
import numpy as np
import pandas as pd

import importlib
import mod_py
importlib.reload(mod_py)

from mod_py import stock_return_risk, portfolio_return, portfolio_risk
print(stock_return_risk("AAPL")) #test
print(portfolio_return(["AAPL", "MSFT"], np.array([0.6, 0.4]))) #test
print(portfolio_risk(["AAPL", "MSFT"], np.array([0.6, 0.4]))) #test

"""# Question 2.1

"""

print(stock_return_risk("CSCO"))

"""# Question 2.2"""

print(portfolio_return(["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "CSCO"], np.array([0.2, 0.15, 0.2, 0.15, 0.2, 0.1])))

"""# Question 2.3"""

print(portfolio_risk(["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "CSCO"], np.array([0.2, 0.15, 0.2, 0.15, 0.2, 0.1])))